### ISSUE TITLE
Add contributor information to hub model metadata

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/covid19-forecast-hub#120]
> Good catch @AFg6K7h4fhy2. @sbidari could you edit the metadata to list yourself and/or (as you prefer) the COVIDHub team (with the overall contact email) as model contributors on the Hub models? Thanks!

_Originally posted by @dylanhmorris in https://github.com/CDCgov/covid19-forecast-hub/issues/118#issuecomment-2512740542_

**Comment by AFg6K7h4fhy2** [comment]
If you could change the `.yaml` extension to `.yml` that would be appreciated (quite a minor change; no issue if not changed in this PR).
