### ISSUE TITLE
Generalize exclusion logic

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/covid19-forecast-hub#143]
Should be possible to exclude for any reference date. 
https://github.com/CDCgov/covid19-forecast-hub/blob/62d5c696af663d2d3ca97210b6fe1a758df7a165/src/code/gen_forecast_data.R#L57-L61

Most straightforward approach, I think, would be to have a single excluded_locations (rather than one per date), which has entries for any date for which there are exclusions (and no entry when all locations are to be included).

**Comment by AFg6K7h4fhy2** [comment]
DHM and the author suggest the use of `toml` file. 

```
"2024-11-23" = ["loc_1", "loc_2", "loc_3"]
"2024-12-04" = ["loc_2"]
```
