### ISSUE TITLE
Rename `src/code` to simply `src/` or `code/`?

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/covid19-forecast-hub#155]
Unless/until we are going to have multiple subdirectories for different parts of the codebase (e.g. `src/ensemble/`, `src/visualization/` etc.), I think there can just be one top-level directory named `src` (or `code`, or something else) for all scripts.

**Comment by AFg6K7h4fhy2** [comment]
My preference (feel free to give zero weight) is for `src`.
