### ISSUE TITLE
Changes to the weekly-summaries data files

### ISSUE THREAD

**Issue by sbidari** [CDCgov/covid19-forecast-hub#207]
Two more changes requested for the visualization data

- [ ] add horizon column to `map_data.csv`
- [ ] sort data in forecast.csv alphabetically with US on top

**Comment by AFg6K7h4fhy2** [comment]
Some notes from implementing this. `Rscript get_forecast_data.R --reference_date 2024-12-21 --base_hub_path ../ --horizons_to_include 0 1 2`


One


```
Warning messages:
1: In readLines(file, warn = readLines.warn) :
  incomplete final line found on '../model-metadata/JHU_CSSE-CSSE_Ensemble.yml'
2: In readLines(file, warn = readLines.warn) :
  incomplete final line found on '../model-metadata/MOBS-GLEAM_COVID.yml'
3: In readLines(file, warn = readLines.warn) :
  incomplete final line found on '../model-metadata/NEU_ISI-AdaptiveEnsemble.yml'
```

Two `No exclusions for reference date: 2024-12-21`...the `excluded_locations.toml` file needs to be updated for each reference dates...the only contents of the `excluded_locations.toml` file seem to be:

```
2024-11-23 = [
  "02", 
  "04",
  "05",
  "06",
  "08",
  "10",
  "11",
  "12",
  "13",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "36",
  "37",
  "39",
  "40",
  "42",
  "48",
  "49",
  "51",
  "53",
  "55",
  "56",
  "72",
  "US"
]
```

__Want me to change this?__ i.e. copy these locations across all reference dates and then regenerate each of the files?

**Comment by sbidari** [comment]
Re https://github.com/CDCgov/covid19-forecast-hub/issues/207#issuecomment-2557225366

One: 
I believe these are resulting from the way meta-data files are formatted. I do not want to change anything here since these are submitted by the teams themselves. I am happy to just ignore these warnings until we can't.

Two:
The exclusions for `2024-11-23` exists due to a data reporting issue that affected the indicated locations. We do not expect exclusions for other dates unless something goes wrong again (let's hope not).

**Comment by AFg6K7h4fhy2** [comment]
This issue also covers, in `get_forecast_data.R`, renaming "United States" to "US" in the `location_name` column. This procedure is currently in place for `get_covid_hosp_data.R` and `get_map_data.R`.
