### ISSUE TITLE
update-target-data workflow runs (and fails) on forked repos

### ISSUE THREAD

**Issue by elray1** [CDCgov/covid19-forecast-hub#98]
for example, see the output here: https://github.com/elray1/covid19-forecast-hub-cdc/actions/runs/12055087932

to get this to run only on this primary/upstream repo, you could add a construction similar to this: https://github.com/reichlab/covid19-forecast-hub/blob/master/.github/workflows/upload_to_zoltar.yml#L10

**Comment by sbidari** [comment]
Thank you for bringing this to our attention!
